### ISSUE TITLE
TypeError when placing compass rose 

### ISSUE THREAD

**Issue by stephanmantler** [Hacked-Crew/Magnetic-Declination#11]
The following error is displayed when trying to place a compass rose in QGIS 3.38 (latest):

```
An error has occurred while executing Python code: 

TypeError: a member of enum 'LabelPlacement' is expected not 'LabelPredefinedPointPosition' 
Traceback (most recent call last):
  File "/Users/step/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/MagneticDeclination/Magnetic_declination.py", line 530, in simple_ComputeScale
    return MagneticDeclination.simple_Layer(self)
  File "/Users/step/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/MagneticDeclination/Magnetic_declination.py", line 593, in simple_Layer
    pal_layer.placement=QgsPalLayerSettings.OverPoint
TypeError: a member of enum 'LabelPlacement' is expected not 'LabelPredefinedPointPosition'
```

**Comment by ndavis6** [comment]
I also have this issue, any luck figuring it out?

**Comment by ndavis6** [comment]
Well, that worked for me

**Comment by breau** [comment]
> Well, that worked for me

This fix worked for me as well.
